version: '2'
services:
  db:
    container_name: db
    image: mariadb:latest
    env_file: .env.docker
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  backend:
    container_name: backend
    build:
      context: backend
    volumes:
      - "./backend/src:/app/src"
      - /app/node_modules
    ports:
      - "3333:3333"
    depends_on:
      - db
    env_file: .env.docker
    command: yarn dev
